### ISSUE TITLE
Information on workshops

### ISSUE THREAD

**Issue by aidan-fitz** [MLH/mlh-hackathon-organizer-guide#68]
There's precious little information in this guide about workshops to organize at hackathons, let alone events that help hackers generate ideas and stay on track throughout the event.

Every [Entrepreneurship at Cornell hackathon](http://eship.cornell.edu/hackathons/) starts with a pitch session and a design thinking workshop where hackers learn how to brainstorm based on the problems they're trying to solve. Interspersed throughout the events are 2 or 3 "Progress, Needs, and Goals" (pronounced "ping") or check-in meetings where hackers share their progress and state what they need help with. Check-in meetings might not scale well past 100 hackers (the typical size of an Eship hackathon), but some form of support for hackers who are stuck is needed at events of all sizes.

Some MLH hackathons I've attended, such as BigRed//Hacks, host team-forming mixers, but these can be intimidating and unproductive for autistic or introverted hackers. Pitch sessions help hackers present their ideas in an organized manner but can also be intimidating.

Generally, participants generate the ideas for their hacks starting from either a problem they'd like to solve (such as access to mental health care) or a technology they'd like to use (such as machine learning). Design thinking is well-suited to the first approach; we can refer to [InVision's design thinking guide](https://www.designbetter.co/design-thinking) or a similar resource. I don't know of techniques that work well for the second approach, so if anyone does, I would love to hear from you.

We should add sections about workshops, especially those designed to help hackers generate ideas and make progress on their hacks.

**Comment by theycallmeswift** [comment]
@aidan-fitz I think this is a great idea.  I'd also love to provide more information about MLH Localhost workshops too (http://localhost.mlh.io/).  Are you willing to take a stab at writing something up and sending in a PR?

**Comment by aidan-fitz** [comment]
Sure, I can try, but Cornell is entering its second wave of prelims right now so I will be pretty busy in the next few weeks.

**Comment by theycallmeswift** [comment]
@aidan-fitz sounds good, I'll look forward to reviewing it :)
